
/**
 *
 * @author nazmulchowdhury
 */

public class FPRecognizer extends javax.swing.JFrame implements java.awt.event.ActionListener {

    /**
     * Creates new form FPRecognizer
     */
    public FPRecognizer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        new java.io.File("claimer").mkdirs();
        new java.io.File("templater").mkdirs();
        new java.io.File("matcher").mkdirs();
        
        fas = new javax.swing.JLabel();
        fpv = new javax.swing.JButton();
        fpa = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("fp.jpg")).getImage());

        fas.setFont(new java.awt.Font("Liberation Mono", 1, 16)); // NOI18N
        fas.setText("FingerPrint Recognition System");

        fpv.setFont(new java.awt.Font("Liberation Mono", 1, 16)); // NOI18N
        fpv.setText("Templater Application");
        fpv.setFocusable(false);
        fpv.addActionListener(this);

        fpa.setFont(new java.awt.Font("Liberation Mono", 1, 16)); // NOI18N
        fpa.setText("Matcher Application");
        fpa.setFocusable(false);
        fpa.addActionListener(this);

        cancel.setFont(new java.awt.Font("Liberation Mono", 1, 16)); // NOI18N
        cancel.setText("Quit");
        cancel.setFocusable(false);
        cancel.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fpv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fpa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fas, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(fpv)
                .addGap(56, 56, 56)
                .addComponent(fpa)
                .addGap(50, 50, 50)
                .addComponent(cancel)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
        setTitle("Fingerprint Recognition System");
        setResizable(false);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    @Override
    public void actionPerformed(java.awt.event.ActionEvent e)
    {
        if (e.getSource() == fpv)
        {
            new SysDBAcc().setVisible(true);
            this.setVisible(false);
        }
        else if (e.getSource() == fpa)
        {
            new MatcherApp().setVisible(true);
            this.setVisible(false);
        }
        else if (e.getSource() == cancel)
            System.exit(0);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPRecognizer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FPRecognizer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel fas;
    private javax.swing.JButton fpa;
    private javax.swing.JButton fpv;
    // End of variables declaration//GEN-END:variables
}